# Generated by Django 2.2.1 on 2019-05-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.IntegerField(choices=[(1, 'Shoes'), (2, 'Clothes'), (3, 'Accessoiries')]),
        ),
    ]
