# Generated by Django 2.2.1 on 2019-05-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0005_auto_20190530_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.IntegerField(choices=[('SH', 'Shoes'), ('CS', 'Clothes'), ('AS', 'Accessoiries')]),
        ),
    ]
