# Generated by Django 2.2.1 on 2019-05-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('type', models.CharField(choices=[('Shoes', 1), ('Clothes', 2), ('Accessoiries', 3)], max_length=50)),
            ],
        ),
    ]
