# Generated by Django 2.2.1 on 2019-05-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0002_auto_20190530_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.IntegerField(choices=[('Shoes', 'Shoes'), ('Clothes', 'Clothes'), ('Accessoiries', 'Accessoiries')]),
        ),
    ]
