# Generated by Django 2.2.1 on 2019-05-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0003_auto_20190530_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.IntegerField(choices=[(1, 'Shoes'), (2, 'Clothes'), (3, 'Accessoiries')]),
        ),
    ]
